---

dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: ubuntu1804
    box: ubuntu/bionic64
    memory: 512
    cpus: 1
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected' ]"
  - name: buster
    box: debian/contrib-buster64
    memory: 512
    cpus: 1
  - name: debian9
    box: debian/stretch64
    memory: 512
    cpus: 1
  - name: centos7
    box: centos/7
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks
    ssh_connection:
      pipelining: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
